[project]
name = "fairnesseval"
version = "0.1.0"
description = """This repository is dedicated to the evaluation and testing of a novel fairness approach in machine learning. Automated decision-making systems can potentially introduce biases, raising ethical concerns. This has led to the development of numerous bias mitigation techniques. However, the selection of a fairness-aware model for a specific dataset often involves a process of trial and error, as it is not always feasible to predict in advance whether the mitigation measures provided by the model will meet the user's requirements, or what impact these measures will have on other model metrics such as accuracy and run time. Existing fairness toolkits lack a comprehensive benchmarking framework. To bridge this gap, we present FairnessEval, a framework specifically designed to evaluate fairness in Machine Learning models. FairnessEval streamlines dataset preparation, fairness evaluation, and result presentation, while also offering customization options. In this demonstration, we highlight the functionality of FairnessEval in the selection and validation of fairness-aware models. We compare various approaches and simulate deployment scenarios to showcase FairnessEval effectiveness."""

authors = [
    { name = "Andrea Baraldi", email = "baraldian@gmail.com" },
    { name = "Matteo Brucato", email = "mbrucato@microsoft.com" },
    { name = "Miroslav Dudík", email = "mdudik@microsoft.com" },
    { name = "Francesco Guerra", email = "francesco.guerra@unimore.it" },
    { name = "Matteo Interlandi", email = "mainterl@microsoft.com" },
]

readme = "README.md"
requires-python = ">=3.8"

[project.urls]
homepage = "https://github.com/softlab-unimore/fairnesseval.git"

[project.scripts]
run = "run:main"

dependencies = [
    "numpy",
    "ipywidgets",
    "matplotlib",
]

classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.8",
]
